// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides gift recommendations based on user preferences.
 *
 * - giftRecommendation - A function that takes user preferences and returns a list of gift recommendations.
 * - GiftRecommendationInput - The input type for the giftRecommendation function.
 * - GiftRecommendationOutput - The return type for the giftRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GiftRecommendationInputSchema = z.object({
  preferences: z.string().describe('The preferences of the user for the gift recommendation.'),
});
export type GiftRecommendationInput = z.infer<typeof GiftRecommendationInputSchema>;

const GiftRecommendationOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      productName: z.string().describe('The name of the recommended product.'),
      description: z.string().describe('A brief description of the product.'),
    })
  ).describe('A list of gift recommendations based on the user preferences.'),
});
export type GiftRecommendationOutput = z.infer<typeof GiftRecommendationOutputSchema>;

export async function giftRecommendation(input: GiftRecommendationInput): Promise<GiftRecommendationOutput> {
  return giftRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'giftRecommendationPrompt',
  input: {schema: GiftRecommendationInputSchema},
  output: {schema: GiftRecommendationOutputSchema},
  prompt: `You are a gift recommendation expert for handmade products. Based on the user preferences, you will provide a list of gift recommendations.

User Preferences: {{{preferences}}}

Provide a list of product recommendations with a brief description for each product. Return a JSON object of GiftRecommendationOutputSchema.`, 
});

const giftRecommendationFlow = ai.defineFlow(
  {
    name: 'giftRecommendationFlow',
    inputSchema: GiftRecommendationInputSchema,
    outputSchema: GiftRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
